Review 1
BorisGitSaf/cpp-peer-review pull request #2
Opened 2023-10-18 18:12 UTC by BorisGitSaf

2023-10-20 10:19 UTC, ComradeMashkov requested changes
Хорошее решение. Но я бы использовал `std::equal` и избавился от `Reverse()`.

2023-10-20 10:19 UTC, ComradeMashkov commented on task_2.cpp
> +string Reverse(string_view s, size_t k = 0) {
Так и не нашел, где тебе может пригодиться аргумент `k`. Если он не нужен - тогда и не нужна функция `Reverse`. Можно воспользоваться стандартной функцией `reverse()` или передать в конструктор новой строки итераторы `rbegin` и `rend`.

2023-10-20 10:19 UTC, ComradeMashkov commented on task_2.cpp
> +    string_view GetDomain() const {
Тогда тут придется в качестве возвращаемого значения поставить `std::string`, т.к реверснуть `std::string_view` - не представляется возможным.

2023-10-20 10:19 UTC, ComradeMashkov commented on task_2.cpp
> +        if (other.domain_.substr(0, domain_.size()) == domain_) {
Можно избавить себя от второй лишней проверки и первого использования `substr()`, использовав алгоритм стандартной библиотеки `std::equal()`.

2023-10-20 10:19 UTC, ComradeMashkov commented on task_2.cpp
> +        return found != stop_domains.begin() && (--found)->IsSubDomain(domain);
Очень лаконичное решение!

2023-10-21 12:39 UTC, BorisGitSaf commented on task_2.cpp
> +string Reverse(string_view s, size_t k = 0) {
Объяснюсь
Это рудимент со времен, когда при развороте слова надо было предусмотреть удаление точки из домена, тогда k=1
Но ты прав. Раз это не используется, функция теряет смысл

2023-10-21 12:41 UTC, BorisGitSaf commented on task_2.cpp
> +    string_view GetDomain() const {
Я изначально когда писал, использовал string_view, потому что думал, что передача итераторов в быстрее копирования при перевороте string. Но тест проходит и с ним, так что можно и заменить на string.

2023-10-23 13:01 UTC, ComradeMashkov commented on task_2.cpp
> +string Reverse(string_view s, size_t k = 0) {
Да, так сразу и подумал :)

2023-10-23 13:02 UTC, ComradeMashkov approved these changes
Все исправлено!

2023-10-24 11:49 UTC, merged